### ISSUE TITLE
request: caption in markdown format

### ISSUE THREAD

**Issue by ronligt** [tobiasah/mkdocs-caption#14]
I'm a very happy user of this plugin!

Would it also be possible to use markdown format in the caption?

Now when I try:

```raw
Figure: Test **bold** text

![](image.png)
```

It will show the image with this caption below it: "*Figure 1: Test*" and nothing more. Where I was hoping to see: "*Figure 1: Test **bold** text*"

**Comment by tobiasah** [comment]
that is a cool idea... Need to see how It can be done within the mkdocs processor.

in the meantime I guess you can just use HTML syntax in the caption

**Comment by tobiasah** [comment]
😇 I tried a bit around and came up with the proposal in #16 . Would you mind trying it out before I merge it? Maybe you can give me some feedback if the change works as you had in mind.

**Comment by ronligt** [comment]
That's fantastic news! I would love to try out this new version. How can I do that?

**Comment by tobiasah** [comment]
no need to manually clone, you can simply use pip to install the package directly form a branch. 

```
pip install git+https://github.com/tobiasah/mkdocs-caption.git@markdown_syntax_in_caption
```
