### ISSUE TITLE
Adding the label for a table for cross-referencing not working from the documentation.

### ISSUE THREAD

**Issue by leiwu84** [tobiasah/mkdocs-caption#15]
In the [Quick Start section of the documentation](https://tobiasah.github.io/mkdocs-caption/quick_start/), the example uses round parenthesis ( and ) to define the label (#my-table).

```
Table: table caption (#my-table)
```

I tried but it does not work. I then tried the curved parenthesis { and }, like {#my-table}, and it works. Can you please check it? Thanks.

**Comment by tobiasah** [comment]
Thanks for pointing that out 

Yes the right thing is to use curly barcets. Similar to what is used in the demo https://github.com/tobiasah/mkdocs-caption/blob/main/demo/docs/index.md?plain=1#L39

I will adapt the quickstart
